"""Prayer-time astronomy: a line-for-line port of adhan-swift 1.5.0.

The macOS app calculates with adhan-swift (Batoul Apps, MIT licence). This
module reproduces that library's arithmetic step for step, including its
quirks, so the two builds give the same times to the second. The parity
fixture in `linux/tests/parity.json` is generated by the Swift engine and
checked here; change nothing without regenerating it.

Times are float seconds since the Unix epoch, in UTC, the way `Date` is an
absolute instant in Swift. Swift's IEEE semantics are kept: an impossible
angle yields NaN rather than an exception, and a NaN hour means "this moment
does not happen today" exactly as `settingHour` treats it.
"""

from __future__ import annotations

import calendar as _calendar
import math
import sys
from dataclasses import dataclass, field, replace
from datetime import date as _date, timedelta
from typing import Optional


# MARK: - Swift numeric semantics

def _round(x: float) -> float:
    """Swift's `round`: half away from zero (Python's `round` is banker's)."""
    if not math.isfinite(x):
        return x
    return float(math.floor(x + 0.5)) if x >= 0 else -float(math.floor(-x + 0.5))


def _floor(x: float) -> float:
    return float(math.floor(x)) if math.isfinite(x) else x


def _ceil(x: float) -> float:
    return float(math.ceil(x)) if math.isfinite(x) else x


def _div(a: float, b: float) -> float:
    """IEEE division: x/0 is ±inf, 0/0 is NaN, never an exception."""
    if b == 0:
        if a == 0 or math.isnan(a):
            return math.nan
        return math.copysign(math.inf, a) * math.copysign(1.0, b)
    return a / b


def _asin(x: float) -> float:
    return math.asin(x) if -1.0 <= x <= 1.0 else math.nan


def _acos(x: float) -> float:
    return math.acos(x) if -1.0 <= x <= 1.0 else math.nan


def _is_normal(x: float) -> bool:
    return math.isfinite(x) and x != 0 and abs(x) >= sys.float_info.min


def _normalized_to_scale(value: float, scale: float) -> float:
    return value - (scale * _floor(value / scale))


def _rad(degrees: float) -> float:
    return (degrees * math.pi) / 180.0


def _deg(radians: float) -> float:
    return (radians * 180.0) / math.pi


def _unwound(degrees: float) -> float:
    return _normalized_to_scale(degrees, 360)


def _quadrant_shifted(degrees: float) -> float:
    if -180 <= degrees <= 180:
        return degrees
    return degrees - (360 * _round(degrees / 360))


# MARK: - Astronomical

def mean_solar_longitude(T: float) -> float:
    return _unwound(280.4664567 + 36000.76983 * T + 0.0003032 * T ** 2)


def mean_lunar_longitude(T: float) -> float:
    return _unwound(218.3165 + 481267.8813 * T)


def ascending_lunar_node_longitude(T: float) -> float:
    return _unwound(125.04452 - 1934.136261 * T + 0.0020708 * T ** 2 + T ** 3 / 450000)


def mean_solar_anomaly(T: float) -> float:
    return _unwound(357.52911 + 35999.05029 * T - 0.0001537 * T ** 2)


def solar_equation_of_the_center(T: float, M: float) -> float:
    m = _rad(M)
    term1 = (1.914602 - (0.004817 * T) - (0.000014 * T ** 2)) * math.sin(m)
    term2 = (0.019993 - (0.000101 * T)) * math.sin(2 * m)
    term3 = 0.000289 * math.sin(3 * m)
    return term1 + term2 + term3


def apparent_solar_longitude(T: float, L0: float) -> float:
    longitude = L0 + solar_equation_of_the_center(T, mean_solar_anomaly(T))
    omega = 125.04 - (1934.136 * T)
    lam = longitude - 0.00569 - (0.00478 * math.sin(_rad(omega)))
    return _unwound(lam)


def mean_obliquity_of_the_ecliptic(T: float) -> float:
    return 23.439291 - 0.013004167 * T - 0.0000001639 * T ** 2 + 0.0000005036 * T ** 3


def apparent_obliquity_of_the_ecliptic(T: float, e0: float) -> float:
    O = 125.04 - (1934.136 * T)
    return e0 + (0.00256 * math.cos(_rad(O)))


def mean_sidereal_time(T: float) -> float:
    JD = (T * 36525) + 2451545.0
    theta = 280.46061837 + 360.98564736629 * (JD - 2451545) + 0.000387933 * T ** 2 - T ** 3 / 38710000
    return _unwound(theta)


def nutation_in_longitude(L0: float, Lp: float, omega: float) -> float:
    term1 = (-17.2 / 3600) * math.sin(_rad(omega))
    term2 = (1.32 / 3600) * math.sin(2 * _rad(L0))
    term3 = (0.23 / 3600) * math.sin(2 * _rad(Lp))
    term4 = (0.21 / 3600) * math.sin(2 * _rad(omega))
    return term1 - term2 - term3 + term4


def nutation_in_obliquity(L0: float, Lp: float, omega: float) -> float:
    term1 = (9.2 / 3600) * math.cos(_rad(omega))
    term2 = (0.57 / 3600) * math.cos(2 * _rad(L0))
    term3 = (0.10 / 3600) * math.cos(2 * _rad(Lp))
    term4 = (0.09 / 3600) * math.cos(2 * _rad(omega))
    return term1 + term2 + term3 - term4


def altitude_of_celestial_body(phi: float, delta: float, H: float) -> float:
    term1 = math.sin(_rad(phi)) * math.sin(_rad(delta))
    term2 = math.cos(_rad(phi)) * math.cos(_rad(delta)) * math.cos(_rad(H))
    return _deg(_asin(term1 + term2))


def approximate_transit(L: float, theta0: float, alpha2: float) -> float:
    Lw = L * -1
    m0 = _normalized_to_scale((alpha2 + Lw - theta0) / 360, 1)
    # Near the International Date Line the bound can land m0 on the wrong
    # calendar date; compare with a longitude-based estimate and correct.
    expected = _normalized_to_scale((12.0 - L / 15.0) / 24.0, 1)
    if m0 - expected > 0.5:
        return m0 - 1.0
    if expected - m0 > 0.5:
        return m0 + 1.0
    return m0


def corrected_transit(m0: float, L: float, theta0: float,
                      alpha2: float, alpha1: float, alpha3: float) -> float:
    Lw = L * -1
    theta = _unwound(theta0 + (360.985647 * m0))
    alpha = _unwound(interpolate_angles(alpha2, alpha1, alpha3, m0))
    H = _quadrant_shifted(theta - Lw - alpha)
    dm = H / -360
    return (m0 + dm) * 24


def corrected_hour_angle(m0: float, h0: float, latitude: float, longitude: float,
                         after_transit: bool, theta0: float,
                         alpha2: float, alpha1: float, alpha3: float,
                         delta2: float, delta1: float, delta3: float) -> float:
    Lw = longitude * -1
    term1 = math.sin(_rad(h0)) - (math.sin(_rad(latitude)) * math.sin(_rad(delta2)))
    term2 = math.cos(_rad(latitude)) * math.cos(_rad(delta2))
    H0 = _deg(_acos(_div(term1, term2)))
    m = m0 + (H0 / 360) if after_transit else m0 - (H0 / 360)
    theta = _unwound(theta0 + (360.985647 * m))
    alpha = _unwound(interpolate_angles(alpha2, alpha1, alpha3, m))
    delta = interpolate(delta2, delta1, delta3, m)
    H = theta - Lw - alpha
    h = altitude_of_celestial_body(latitude, delta, H)
    term3 = h - h0
    term4 = 360 * math.cos(_rad(delta)) * math.cos(_rad(latitude)) * math.sin(_rad(H))
    dm = _div(term3, term4)
    return (m + dm) * 24


def interpolate(y2: float, y1: float, y3: float, n: float) -> float:
    a = y2 - y1
    b = y3 - y2
    c = b - a
    return y2 + ((n / 2) * (a + b + (n * c)))


def interpolate_angles(y2: float, y1: float, y3: float, n: float) -> float:
    a = _unwound(y2 - y1)
    b = _unwound(y3 - y2)
    c = b - a
    return y2 + ((n / 2) * (a + b + (n * c)))


def _trunc_div(a: int, b: int) -> int:
    """Swift's integer division truncates toward zero."""
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b >= 0) else -q


def julian_day(year: int, month: int, day: int, hours: float = 0) -> float:
    Y = year if month > 2 else year - 1
    M = month if month > 2 else month + 12
    D = day + (hours / 24)
    A = _trunc_div(Y, 100)
    B = 2 - A + _trunc_div(A, 4)
    i0 = int(365.25 * (Y + 4716))
    i1 = int(30.6001 * (M + 1))
    return i0 + i1 + D + B - 1524.5


def julian_century(JD: float) -> float:
    return (JD - 2451545.0) / 36525


def is_leap_year(year: int) -> bool:
    if year % 4 != 0:
        return False
    if year % 100 == 0 and year % 400 != 0:
        return False
    return True


def _seasonal(a: float, b: float, c: float, d: float, dyy: float) -> float:
    if dyy < 91:
        return a + (b - a) / 91.0 * dyy
    if dyy < 137:
        return b + (c - b) / 46.0 * (dyy - 91)
    if dyy < 183:
        return c + (d - c) / 46.0 * (dyy - 137)
    if dyy < 229:
        return d + (c - d) / 46.0 * (dyy - 183)
    if dyy < 275:
        return c + (b - c) / 46.0 * (dyy - 229)
    return b + (a - b) / 91.0 * (dyy - 275)


def season_adjusted_morning_twilight(latitude: float, day: int, year: int, sunrise: float) -> float:
    lat = abs(latitude)
    a = 75 + ((28.65 / 55.0) * lat)
    b = 75 + ((19.44 / 55.0) * lat)
    c = 75 + ((32.74 / 55.0) * lat)
    d = 75 + ((48.10 / 55.0) * lat)
    adjustment = _seasonal(a, b, c, d, float(days_since_solstice(day, year, latitude)))
    return sunrise + _round(adjustment * -60.0)


def season_adjusted_evening_twilight(latitude: float, day: int, year: int, sunset: float, shafaq: str) -> float:
    lat = abs(latitude)
    if shafaq == "ahmer":
        a = 62 + ((17.40 / 55.0) * lat)
        b = 62 - ((7.160 / 55.0) * lat)
        c = 62 + ((5.120 / 55.0) * lat)
        d = 62 + ((19.44 / 55.0) * lat)
    elif shafaq == "abyad":
        a = 75 + ((25.60 / 55.0) * lat)
        b = 75 + ((7.160 / 55.0) * lat)
        c = 75 + ((36.84 / 55.0) * lat)
        d = 75 + ((81.84 / 55.0) * lat)
    else:  # general
        a = 75 + ((25.60 / 55.0) * lat)
        b = 75 + ((2.050 / 55.0) * lat)
        c = 75 - ((9.210 / 55.0) * lat)
        d = 75 + ((6.140 / 55.0) * lat)
    adjustment = _seasonal(a, b, c, d, float(days_since_solstice(day, year, latitude)))
    return sunset + _round(adjustment * 60.0)


def days_since_solstice(day_of_year: int, year: int, latitude: float) -> int:
    northern_offset = 10
    southern_offset = 173 if is_leap_year(year) else 172
    days_in_year = 366 if is_leap_year(year) else 365
    if latitude >= 0:
        days = day_of_year + northern_offset
        if days >= days_in_year:
            days -= days_in_year
    else:
        days = day_of_year - southern_offset
        if days < 0:
            days += days_in_year
    return days


# MARK: - Solar coordinates and time

@dataclass(frozen=True)
class SolarCoordinates:
    declination: float
    right_ascension: float
    apparent_sidereal_time: float

    @classmethod
    def at(cls, jd: float) -> "SolarCoordinates":
        T = julian_century(jd)
        L0 = mean_solar_longitude(T)
        Lp = mean_lunar_longitude(T)
        omega = ascending_lunar_node_longitude(T)
        lam = _rad(apparent_solar_longitude(T, L0))
        theta0 = mean_sidereal_time(T)
        dpsi = nutation_in_longitude(L0, Lp, omega)
        deps = nutation_in_obliquity(L0, Lp, omega)
        e0 = mean_obliquity_of_the_ecliptic(T)
        eapp = _rad(apparent_obliquity_of_the_ecliptic(T, e0))
        declination = _deg(_asin(math.sin(eapp) * math.sin(lam)))
        right_ascension = _unwound(_deg(math.atan2(math.cos(eapp) * math.sin(lam), math.cos(lam))))
        sidereal = theta0 + (((dpsi * 3600) * math.cos(_rad(e0 + deps))) / 3600)
        return cls(declination, right_ascension, sidereal)


def _day_start(ymd: tuple[int, int, int]) -> float:
    y, m, d = ymd
    return float(_calendar.timegm((y, m, d, 0, 0, 0, 0, 0, 0)))


def _setting_hour(ymd: tuple[int, int, int], value: float) -> Optional[float]:
    """`DateComponents.settingHour` resolved against the UTC calendar."""
    if not _is_normal(value):
        return None
    hours = math.floor(value)
    minutes = math.floor((value - hours) * 60)
    seconds = math.floor((value - (hours + minutes / 60)) * 60 * 60)
    return _day_start(ymd) + hours * 3600 + minutes * 60 + seconds


class SolarTime:
    def __init__(self, ymd: tuple[int, int, int], latitude: float, longitude: float):
        self.ymd = ymd
        self.latitude = latitude
        self.longitude = longitude
        jd = julian_day(ymd[0], ymd[1], ymd[2], 0)
        self.prev = SolarCoordinates.at(jd - 1)
        self.solar = SolarCoordinates.at(jd)
        self.next = SolarCoordinates.at(jd + 1)
        s, p, n = self.solar, self.prev, self.next
        self.approx_transit = approximate_transit(longitude, s.apparent_sidereal_time, s.right_ascension)
        solar_altitude = -50.0 / 60.0
        transit = corrected_transit(self.approx_transit, longitude, s.apparent_sidereal_time,
                                    s.right_ascension, p.right_ascension, n.right_ascension)
        sunrise = self._hour_angle(solar_altitude, after_transit=False)
        sunset = self._hour_angle(solar_altitude, after_transit=True)
        self.transit = _setting_hour(ymd, transit)
        self.sunrise = _setting_hour(ymd, sunrise)
        self.sunset = _setting_hour(ymd, sunset)
        self.valid = None not in (self.transit, self.sunrise, self.sunset)

    def _hour_angle(self, angle: float, after_transit: bool) -> float:
        s, p, n = self.solar, self.prev, self.next
        return corrected_hour_angle(
            self.approx_transit, angle, self.latitude, self.longitude, after_transit,
            s.apparent_sidereal_time,
            s.right_ascension, p.right_ascension, n.right_ascension,
            s.declination, p.declination, n.declination,
        )

    def time_for_solar_angle(self, angle: float, after_transit: bool) -> Optional[float]:
        return _setting_hour(self.ymd, self._hour_angle(angle, after_transit))

    def afternoon(self, shadow_length: float) -> Optional[float]:
        tangent = abs(self.latitude - self.solar.declination)
        inverse = shadow_length + math.tan(_rad(tangent))
        angle = _deg(math.atan(_div(1.0, inverse)))
        return self.time_for_solar_angle(angle, after_transit=True)


# MARK: - Parameters

METHODS = (
    "muslimWorldLeague", "egyptian", "karachi", "ummAlQura", "dubai",
    "moonsightingCommittee", "northAmerica", "kuwait", "qatar", "singapore",
    "tehran", "turkey", "other",
)
HIGH_LATITUDE_RULES = ("middleOfTheNight", "seventhOfTheNight", "twilightAngle")
SHAFI, HANAFI = 1, 2
PRAYERS = ("fajr", "sunrise", "dhuhr", "asr", "maghrib", "isha")


def _adjustments(**minutes: int) -> dict[str, int]:
    return {p: int(minutes.get(p, 0)) for p in PRAYERS}


@dataclass
class CalculationParameters:
    fajr_angle: float
    isha_angle: float
    method: str = "other"
    maghrib_angle: Optional[float] = None
    isha_interval: int = 0
    madhab: int = SHAFI
    high_latitude_rule: Optional[str] = None
    adjustments: dict = field(default_factory=_adjustments)
    rounding: str = "nearest"
    shafaq: str = "general"
    method_adjustments: dict = field(default_factory=_adjustments)

    def night_portions(self, latitude: float) -> tuple[float, float]:
        rule = self.high_latitude_rule or recommended_high_latitude_rule(latitude)
        if rule == "middleOfTheNight":
            return (1 / 2, 1 / 2)
        if rule == "seventhOfTheNight":
            return (1 / 7, 1 / 7)
        return (self.fajr_angle / 60, self.isha_angle / 60)

    def copy(self) -> "CalculationParameters":
        return replace(self, adjustments=dict(self.adjustments),
                       method_adjustments=dict(self.method_adjustments))


def recommended_high_latitude_rule(latitude: float) -> str:
    return "seventhOfTheNight" if latitude > 48 else "middleOfTheNight"


def method_params(method: str) -> CalculationParameters:
    P = CalculationParameters
    if method == "muslimWorldLeague":
        return P(18, 17, method, method_adjustments=_adjustments(dhuhr=1))
    if method == "egyptian":
        return P(19.5, 17.5, method, method_adjustments=_adjustments(dhuhr=1))
    if method == "karachi":
        return P(18, 18, method, method_adjustments=_adjustments(dhuhr=1))
    if method == "ummAlQura":
        return P(18.5, 0, method, isha_interval=90)
    if method == "dubai":
        return P(18.2, 18.2, method, method_adjustments=_adjustments(sunrise=-3, dhuhr=3, asr=3, maghrib=3))
    if method == "moonsightingCommittee":
        return P(18, 18, method, method_adjustments=_adjustments(dhuhr=5, maghrib=3))
    if method == "northAmerica":
        return P(15, 15, method, method_adjustments=_adjustments(dhuhr=1))
    if method == "kuwait":
        return P(18, 17.5, method)
    if method == "qatar":
        return P(18, 0, method, isha_interval=90)
    if method == "singapore":
        return P(20, 18, method, method_adjustments=_adjustments(dhuhr=1), rounding="up")
    if method == "tehran":
        return P(17.7, 14, method, maghrib_angle=4.5)
    if method == "turkey":
        return P(18, 17, method, method_adjustments=_adjustments(sunrise=-7, dhuhr=5, asr=4, maghrib=7))
    return P(0, 0, "other")


# MARK: - Prayer times

def rounded_minute(t: float, rounding: str = "nearest") -> float:
    whole = math.floor(t)
    second = whole % 60
    start = whole - second
    if rounding == "nearest":
        return float(start + 60 * _round(second / 60))
    if rounding == "up":
        return float(start + 60 * _ceil(second / 60))
    return float(whole)


def _add_day(ymd: tuple[int, int, int], days: int = 1) -> tuple[int, int, int]:
    d = _date(*ymd) + timedelta(days=days)
    return (d.year, d.month, d.day)


class PrayerTimes:
    """One day's six markers, as UTC instants. Build with `PrayerTimes.compute`,
    which returns None where adhan-swift's failable initialiser returns nil."""

    def __init__(self, ymd, latitude, longitude, params, times):
        self.ymd = ymd
        self.latitude = latitude
        self.longitude = longitude
        self.params = params
        self.fajr, self.sunrise, self.dhuhr, self.asr, self.maghrib, self.isha = times

    def time(self, prayer: str) -> float:
        return getattr(self, prayer)

    @classmethod
    def compute(cls, latitude: float, longitude: float, ymd: tuple[int, int, int],
                params: CalculationParameters) -> Optional["PrayerTimes"]:
        year = ymd[0]
        day_of_year = _date(*ymd).timetuple().tm_yday
        tomorrow = _add_day(ymd)

        solar = SolarTime(ymd, latitude, longitude)
        tomorrow_solar = SolarTime(tomorrow, latitude, longitude)
        # Swift's SolarTime initialiser fails unless transit, sunrise and
        # sunset all exist, for tomorrow as much as for today.
        if not solar.valid or not tomorrow_solar.valid:
            return None
        sunrise_date = solar.sunrise
        sunset_date = solar.sunset
        tomorrow_sunrise = tomorrow_solar.sunrise

        fajr: Optional[float] = None
        isha: Optional[float] = None
        sunrise = solar.sunrise
        maghrib = solar.sunset
        dhuhr = solar.transit
        asr = solar.afternoon(float(params.madhab))

        night = tomorrow_sunrise - sunset_date
        moonsighting = params.method == "moonsightingCommittee"

        fajr = solar.time_for_solar_angle(-params.fajr_angle, after_transit=False)
        if moonsighting and latitude >= 55:
            fajr = sunrise_date - night / 7

        if moonsighting:
            safe_fajr = season_adjusted_morning_twilight(latitude, day_of_year, year, sunrise_date)
        else:
            safe_fajr = sunrise_date - params.night_portions(latitude)[0] * night
        if fajr is None or fajr < safe_fajr:
            fajr = safe_fajr

        if params.isha_interval > 0:
            isha = maghrib + params.isha_interval * 60
        else:
            isha = solar.time_for_solar_angle(-params.isha_angle, after_transit=True)
            if moonsighting and latitude >= 55:
                isha = sunset_date + night / 7
            if moonsighting:
                safe_isha = season_adjusted_evening_twilight(latitude, day_of_year, year, sunset_date, params.shafaq)
            else:
                safe_isha = sunset_date + params.night_portions(latitude)[1] * night
            if isha is None or isha > safe_isha:
                isha = safe_isha

        if params.maghrib_angle is not None:
            angled = solar.time_for_solar_angle(-params.maghrib_angle, after_transit=True)
            # Maghrib by angle is only used when it lands between sunset and Isha.
            if angled is not None and sunset_date < angled and (isha is None or isha > angled):
                maghrib = angled

        raw = {"fajr": fajr, "sunrise": sunrise, "dhuhr": dhuhr,
               "asr": asr, "maghrib": maghrib, "isha": isha}
        if any(v is None for v in raw.values()):
            return None

        final = []
        for prayer in PRAYERS:
            t = raw[prayer] + params.adjustments[prayer] * 60 + params.method_adjustments[prayer] * 60
            final.append(rounded_minute(t, params.rounding))
        return cls(ymd, latitude, longitude, params, tuple(final))


class SunnahTimes:
    def __init__(self, middle_of_the_night: float, last_third_of_the_night: float):
        self.middle_of_the_night = middle_of_the_night
        self.last_third_of_the_night = last_third_of_the_night

    @classmethod
    def compute(cls, times: PrayerTimes) -> Optional["SunnahTimes"]:
        tomorrow = PrayerTimes.compute(times.latitude, times.longitude, _add_day(times.ymd), times.params)
        if tomorrow is None:
            return None
        night = tomorrow.fajr - times.maghrib
        return cls(rounded_minute(times.maghrib + night / 2),
                   rounded_minute(times.maghrib + night * (2 / 3)))
