# Cask for Barakah — prayer times, iqama reminders, and media that stops.
# https://github.com/TheOddjobShop/barakah
#
# Generated by `make cask`, which substitutes the real checksum of the built
# disk image. Copy the output into justin06lee/homebrew-tap/Casks/barakah.rb.
cask "barakah" do
  version "__VERSION__"
  sha256 "__SHA256__"

  url "https://github.com/TheOddjobShop/barakah/releases/download/v#{version}/Barakah_#{version}_universal.dmg"
  name "Barakah"
  desc "Prayer times with iqama reminders that pause your media"
  homepage "https://github.com/TheOddjobShop/barakah"

  depends_on macos: ">= :sonoma"

  app "Barakah.app"

  zap trash: [
    "~/Library/Application Support/Barakah",
    "~/Library/Caches/Barakah",
    "~/Library/Preferences/dev.justin06lee.barakah.plist",
  ]

  caveats <<~EOS
    Barakah asks for three permissions the first time it needs them:

      Location      to calculate prayer times for where you are
      Notifications  for iqama reminders
      Automation     to pause Spotify, Music, VLC and QuickTime

    Prayer times are computed on your Mac and work offline. The only network
    call is Apple's geocoder, used to turn coordinates into a place name.

    It ships no adhan recording, because every recording of the adhan is
    copyrighted even though the words are not. The default sound is a
    synthesised chime. To use a real one, point Barakah at a file you have
    rights to under Settings > Athan, or drop it into:

      ~/Library/Application Support/Barakah/Athan/
  EOS
end
